# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-11 22:59
from __future__ import unicode_literals

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorLayerPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_lasagna_colorlayerplugin', serialize=False, to='cms.CMSPlugin')),
                ('color', colorfield.fields.ColorField(max_length=18, verbose_name='color')),
            ],
            options={
                'verbose_name': 'Color layer',
                'verbose_name_plural': 'Color layer',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='LasagnaPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_lasagna_lasagnaplugin', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(blank=True, default='', max_length=400, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Lasagna',
                'verbose_name_plural': 'Lasagna',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='OpacityModifierPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_lasagna_opacitymodifierplugin', serialize=False, to='cms.CMSPlugin')),
                ('opacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='opacity (%)')),
            ],
            options={
                'verbose_name': 'Opacity modifier',
                'verbose_name_plural': 'Opacity modifiers',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='VerticalAlignmentModifierPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_lasagna_verticalalignmentmodifierplugin', serialize=False, to='cms.CMSPlugin')),
                ('alignment', models.PositiveSmallIntegerField(choices=[(0, 'top'), (1, 'middle'), (2, 'bottom')], default=0, verbose_name='alignment')),
            ],
            options={
                'verbose_name': 'Vertical alignment modifier',
                'verbose_name_plural': 'Vertical alignment modifiers',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
