# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-07 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_lasagna', '0002_auto_20180102_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageanchormodifierplugin',
            name='object_fit',
            field=models.CharField(choices=[('fill', 'Fill the container'), ('contain', 'Fit into the container'), ('cover', 'Fill the container and maintain the aspect ratio'), ('none', "Don't resize"), ('scale-down', 'Scale down to fit into the container')], default='cover', max_length=10, verbose_name='resize'),
        ),
        migrations.AlterField(
            model_name='verticalalignmentmodifierplugin',
            name='alignment',
            field=models.PositiveSmallIntegerField(choices=[(0, 'top'), (1, 'middle'), (2, 'bottom')], default=0, verbose_name='alignment'),
        ),
    ]
